#!/bin/bash
# Test basic functionality for incremental backups

dbname=$1
debug=1
#DBDIR=$2

[[ "$debug" == "1" ]] && set -x

if [[ -z "$dbname" ]] ; then
  [[ "$debug" == "1" ]] && set -x
  echo dbname missing
  exit 1
fi

function failexit
{
  [[ "$debug" == "1" ]] && set -x
    echo "Failed $1"
    exit -1
}

function make_base {
  [[ "$debug" == "1" ]] && set -x
  basename=${TMPDIR}/backups/base.tar
  backuplist+=(base.tar)
  comdb2ar c -I create -b ${TMPDIR}/increment ${DBDIR}/${dbname}.lrl > $basename
  #echo $cmd
  #$cmd
}

function make_backup {
  [[ "$debug" == "1" ]] && set -x
  fullbackupname=$1
  backupname=${fullbackupname%.*}.tar
  backuplist+=($backupname)
  comdb2ar c -I inc -b ${TMPDIR}/increment ${DBDIR}/${dbname}.lrl > ${TMPDIR}/backups/${backupname}
  #echo $cmd
  #$cmd
}

function test_restoredb {
  [[ "$debug" == "1" ]] && set -x
  testname=$1
  restorecmd="cat "
  for i in $(seq 0 $2); do
    restorecmd="$restorecmd <(${backuplist[i]}) "
  done

  restorecmd="$restorecmd | comdb2ar x -I restore ${TMPDIR}/restore/ ${TMPDIR}/restore"
  $restorecmd

  comdb2 --lrl ${TMPDIR}/restore/$dbname.lrl ${dbname}_restore &
  dbpid=$!

  cnt=0
  cdb2sql ${CDB2_OPTIONS} $dbname default "select 1"
  while [[ $? != 0 && $cnt -le 30 ]]; do
      cdb2sql ${CDB2_OPTIONS} $dbname default "select 1"
      let cnt=cnt+1
      sleep 1 
  done

  cb2sql ${CDB2_OPTIONS} -f $1 $dbname default > $output 2>&1
  expected_output=$(cat ${testname}.out)

  if [[ "$output" != "$expected_output" ]] ; then
    echo "  ^^^^^^^^^^^^"
    echo "The above testcase (${testname}) has failed!!!"
    echo " "
    echo "Use 'diff <expected-output> <my-output>' to see why:"
    echo "> diff ${PWD}/{$testname.out.$output}"
    echo " "
    diff $testname.out $output
    echo " "
    exit 1
  fi

  kill $dbpid
  rm -rf ${TMPDIR}/restore/*
}

function resetdb {
  [[ "$debug" == "1" ]] && set -x
  backuplist=()
  rm -rf ${TMPDIR}/backups ${TMPDIR}/restore ${TMPDIR}/increment
  mkdir -p ${TMPDIR}/backups ${TMPDIR}/restore ${TMPDIR}/increment

  cdb2sql ${CDB2_OPTIONS} $dbname default "DROP TABLE t1"
  make_base
  cdb2sql ${CDB2_OPTIONS} $dbname default "CREATE TABLE t1  { `cat t1.csc2 ` }" || failexit "create failed"
  make_backup create_table
}

# BASIC FUNCTIONALITY TEST
resetdb

for statement in `ls t1*.stmt`; do
  cb2sql ${CDB2_OPTIONS} -f $statement $dbname default
  make_backup statement
done

counter=0

for testreq in `ls t1*.req`; do
  test_restoredb testreq counter
  ((counter++))
done

# PUSH NEXT TEST FOR RECOVERY WITH LOG HOLES
resetdb
for i in $(seq 1 10); do
  cdb2sql ${CDB2_OPTIONS} $dbname default "exec procedure sys.cmd.send('pushnext')"
done
cdb2sql ${CDB2_OPTIONS} -f t1-1_insert.stmt $dbname default
make_backup push_next_inserts
test_restoredb t2.req 1

echo "Test Successful"
exit 0
